### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by Cherkah** [goodell/highlight#8]
hello

how can i use your script?
first i export the script:
`export HIGHLIGHT=PATH/TO/HIGLIGHT`
after i call the script in my cmd:
 `cat /var/log/pacman.log | grep "installed" | tail -n 100 | highlight --color=red installed`
result: 
`bash: HIGHLIGHT cmd not found`
but i have nothing.
im running a manjaro distro.
should i've to install a perl package? if yes which one?

plus, when i consult `$HIGHLIGHT_COLOR` i had no output

thx

**Comment by Cherkah** [comment]
ok my bad
i 've succed to correct my self

thank for your script

**Comment by Cherkah** [comment]
i have a small issue when i use highlight.

`--filter green,installed ` will give an green output. 
but `--filter green,_installed_ --filter yellow,_**re**installed_` will output the pattern 'installed' green and  the '**_re_**' of reinstalled white.
Highlight doesn't consider the word 'reinstalled' as an different word.
Does it possible to change that, so as to the script greps pattern that are delimitated by space?

thanks

**Comment by goodell** [comment]
Try using a pattern will prevent the overly-broad pattern from matching, such as by using a zero-width assertion like `\b`. Compare the output on your system between these two commands:

```
echo "this is installed ; this is reinstalled" | highlight --filter green,installed --filter yellow,reinstalled
echo "this is installed ; this is reinstalled" | highlight --filter 'green,\binstalled' --filter yellow,reinstalled
```

![image](https://user-images.githubusercontent.com/78560/115926476-c1696b00-a437-11eb-96cc-4238a6dddfa3.png)
